name: Auto commit

on:

  push:
    branches:
      - master
      
  schedule:
  - cron: "00 17 * * *" # See https://crontab.guru/

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG 
        run: echo "::debug::Ref = ${{github.ref}}"
      - uses: actions/checkout@v3      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          TZ='Asia/Ho_Chi_Minh' d=`date -u -d '+7 hours' '+%Y-%m-%dT%H:%M:%S+07:00'`
          echo -e "This is the first commit of $d" > LAST_UPDATED
          #d=`date -u -d '+7 hours' '+%Y-%m-%dT%H:%M:%S+07:00'` && echo "This is the first commit of $d" > LAST_UPDATED
          # echo $d > LAST_UPDATED
          
      - name: Commit changes
        run: |
          git config --local user.email "taphuc1@gmail.com"
          git config --local user.name "andrew-taphuc"
          git add -A
          
          # arr[0]="andrew-taphuc: make it green"
          # arr[1]="andrew-taphuc: make it green"
          # arr[2]="andrew-taphuc: make it green"
          # arr[3]="andrew-taphuc: make it green"
          # arr[4]="andrew-taphuc: make it green"
          # arr[5]="andrew-taphuc: make it green"
          # arr[6]="andrew-taphuc: make it green"
          # arr[7]="andrew-taphuc: make it green"
          # arr[8]="andrew-taphuc: make it green"
          # arr[9]="andrew-taphuc: make it green"
          
          # rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "andrew-taphuc: make it green"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
